# Generated by Django 2.0 on 2019-06-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_name', models.CharField(max_length=10)),
                ('e_add', models.CharField(max_length=10)),
                ('e_dept', models.CharField(max_length=15)),
            ],
        ),
    ]
